Connect/Controllers/DashboardController.cs
using ApplicationServices;
using Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Models;
using System.Web;
using System.Web.Mvc;

namespace Connect.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {
        public UserManager UserManager
        {
            get
            {
                return Request.GetOwinContext().GetUserManager<UserManager>();
            }
        }

        private readonly IDashboardManager dashboardInfoProvider;
        private readonly ICommonInfoManager commonInfoProvider;
        private readonly IUserInfoProvider userInfoProvider;

        public DashboardController(ICommonInfoManager commonInfoProvider, IUserInfoProvider userInfoProvider, IDashboardManager dashboardInfoProvider)
        {
            this.commonInfoProvider = commonInfoProvider;
            this.userInfoProvider = userInfoProvider;
            this.dashboardInfoProvider = dashboardInfoProvider;
        }

        [HttpGet]
        public ActionResult UserDashboard()
        {
            var userId = int.Parse(User.Identity.GetUserId());
            var isRecruiter = UserManager.IsInRole(userId, "Recruiter");
            var userDashboardProfile = userInfoProvider.GetUserDashboardProfile(userId);

            if (isRecruiter)
            {
                Session["userName"] = User.Identity.GetUserName();
                return View("RecruiterDashboard/RecruiterDashboard", userDashboardProfile);
            }

            return View(userDashboardProfile);
        }

        [HttpGet]
        public ActionResult TheWall()
        {
            var activityArea = commonInfoProvider.GetActivityArea();

            return PartialView(new TheWall(activityArea));
        }

        [HttpGet]
        public ActionResult UserSuitiblePositions(int? sectorId, int? countryId)
        {
            var userId = User.Identity.GetUserId();
            var suitiblePositions = dashboardInfoProvider.GetSuitiblePositions(sectorId, countryId, int.Parse(userId));
            return PartialView(suitiblePositions);
        }

        [HttpGet]
        public ActionResult CandidateSuggestions(int positionId)
        {
            var suitiblePositions = dashboardInfoProvider.GetCandidateSuggestions(null, null, positionId);
            return PartialView("RecruiterDashboard/CandidateSuggestions", suitiblePositions);
        }
    }
}

Connect/Controllers/ProfileController.cs
using System.Web;
using System.Web.Mvc;

using ApplicationServices;
using Connect.Helpers;
using Models;
using Models.Profile;
using Data;
using Microsoft.AspNet.Identity.Owin;
using Data.Repository.Implementation;
using Microsoft.AspNet.Identity;
using System;

namespace Connect.Controllers
{
    public class ProfileController : BaseController
    {
        public UserManager UserManager
        {
            get
            {
                return Request.GetOwinContext().GetUserManager<UserManager>();
            }
        }

        private readonly IUserInfoProvider userInfoProvider;
        private readonly ISkillsApplicationService skillsApplicationService;
        private readonly ICommonInfoManager commonInfoProvider;
        private readonly IProfileApplicationService profileApplicationService;

        public ProfileController(IUserInfoProvider userInfoProvider, ISkillsApplicationService skillsApplicationService, ICommonInfoManager commonInfoProvider, IProfileApplicationService profileApplicationService)
        {
            this.userInfoProvider = userInfoProvider;
            this.skillsApplicationService = skillsApplicationService;
            this.commonInfoProvider = commonInfoProvider;
            this.profileApplicationService = profileApplicationService;
        }
        
        public ActionResult SetUserRole(UserType userType)
        {
            var userId = User.Identity.GetUserId();
            var userName = User.Identity.GetUserName();

            switch (userType)
            {
                case UserType.Recruiter:
                    UserManager.AddToRole(int.Parse(userId), "Recruiter");
                    break;
                case UserType.Candidate:
                    UserManager.AddToRole(int.Parse(userId), "Candidate");
                    break;
                default:
                    throw new ArgumentException("No such user type");
            }

            return Json(new { RedirectUrl = Url.Content("~/Profile/Profile?userName=" + userName) }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public new ActionResult Profile(string userName)
        {
            var user = UserManager.FindByName(userName);

            var isRecruiter = UserManager.IsInRole(user.Id, "Recruiter");
            var currentUser = userInfoProvider.GetUserProfile(user.Id);

            if (isRecruiter)
            {
                Session["userNameReadOnly"] = userName;
                if (User.Identity.GetUserName().Equals(userName))
                {
                    Session["userName"] = userName;
                    currentUser.CanEditProfile = true;
                    return View("RecruiterProfile");
                }

                return View("RecruiterProfileReadOnly");
            }

            if (User.Identity.GetUserName().Equals(userName))
            {
                Session["userName"] = userName;
                currentUser.CanEditProfile = true;
                return View(currentUser);
            }

            return View("ProfileReadOnly", currentUser);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NavigationProfileInfo()
        {
            var userId = User.Identity.GetUserId();
            var userDashboardProfile = userInfoProvider.GetUserDashboardProfile(int.Parse(userId));

            return PartialView(userDashboardProfile);
        }

        [Authorize]
        [HttpGet]
        [ChildActionOnly]
        public ActionResult ProfileBasicInfo(string userName)
        {
            var user = UserManager.FindByName(userName);
            var currentUser = userInfoProvider.GetBasicUserInfo(user.Id);

            if (User.Identity.GetUserName().Equals(userName))
            {
                currentUser.CanEditProfile = true;
            }

            return PartialView(currentUser);
        }

        [Authorize]
        [HttpGet]
        [OutputCache(Duration = 60 * 60)]
        public ActionResult Qualifications(string userName)
        {
            var user = UserManager.FindByName(userName);
            var currentUser = userInfoProvider.GetUserProfile(user.Id);

            if (User.Identity.GetUserName().Equals(userName))
            {
                currentUser.CanEditProfile = true;
            }

            return PartialView(currentUser);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddExperience(ExperienceViewModel experience)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();

                experience.UserId = int.Parse(userId);
                userInfoProvider.AddExperience(experience, UserManager);

                return PartialView("Experience", experience);
            }

            return PartialView(experience);
        }

        [Authorize]
        [HttpGet]
        [OutputCache(Duration = 60 * 60)]
        public ActionResult CreatePosition()
        {
            return PartialView("~/Views/RecruiterProfile/AddPosition.cshtml", new AddPosition());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePosition(AddPosition newPosition)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                newPosition.UserId = int.Parse(userId);
                var position = profileApplicationService.Execute(newPosition);

                return Json(position.PositionId, JsonRequestBehavior.AllowGet);
            }

            return Json(new { error = "Could not create position" }, JsonRequestBehavior.DenyGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetOpenedPositions(string userName)
        {
            var user = UserManager.FindByName(userName);
            var openedPositions = userInfoProvider.GetCreatedPositions(user.Id);
            return PartialView("~/Views/Dashboard/RecruiterDashboard/CreatedPositions.cshtml", openedPositions);
        }
    }
}

Connect/Views/Shared/_CompanyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connect</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*TODO: Move scripts to bundle to be loaded for the places they are needed.*@
    <script src="~/Scripts/ConnectScripts/Global/connect.js"></script>
    <script src="~/Scripts/ConnectScripts/Global/connect.utils.js"></script>
    <script type="text/javascript">
        $("#file").filestyle({ buttonName: "btn btn-default col-lg-12" });
        $("#file").filestyle("size", "md");
        $(":file").filestyle('input', false);
        $("#file").filestyle('buttonText', 'Change pucture');
    </script>
    <script src="~/Scripts/ConnectScripts/Navigation/NavigationManager.js"></script>
    @RenderSection("ProfileScripts", required: false)
    @RenderSection("DashboardScripts", required: false)
</body>
</html>

Connect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connect</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href='@Url.Action("UserDashboard", "Dashboard")'>
                    <img src="~/Content/Images/C.png" style="width: 49px;" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class=""><i class="glyphicon glyphicon-bell"></i></a>
                    </li>
                    <li>
                        <a href="#" class=""><i class="glyphicon glyphicon-envelope"></i></a>
                    </li>
                    <li>
                        <a id="nav-profile" href="#"><i class="glyphicon glyphicon-user"></i></a>
                        <div class="nav-select-option" data-toggle="#nav-profile">
                            @Html.Action("NavigationProfileInfo", "Profile")
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*TODO: Move scripts to bundle to be loaded for the places they are needed.*@
    <script src="~/Scripts/ConnectScripts/Global/connect.js"></script>
    <script src="~/Scripts/ConnectScripts/BusinessInfo/connect.companies.js"></script>
    <script src="~/Scripts/ConnectScripts/Global/connect.utils.js"></script>
    <script type="text/javascript">
        $("#file").filestyle({ buttonName: "btn btn-default col-lg-12" });
        $("#file").filestyle("size", "md");
        $(":file").filestyle('input', false);
        $("#file").filestyle('buttonText', 'Change pucture');
    </script>
    <script src="~/Scripts/ConnectScripts/Profile/profile-basic-info.js"></script>
    <script src="~/Scripts/ConnectScripts/Navigation/NavigationManager.js"></script>
    @RenderSection("ProfileScripts", required: false)
    @RenderSection("DashboardScripts", required: false)
</body>
</html>