Connect/Controllers/BusinessInfoController.cs
namespace Connect.Controllers
{
    using System.Web.Mvc;

    using ApplicationServices;
    using Models;
    using Helpers;
    using Data;
    using System.Web;
    using Data.Repository.Implementation;
    using Microsoft.AspNet.Identity.Owin;
    using Microsoft.AspNet.Identity;

    [Authorize]
    public class BusinessInfoController : BaseController
    {
        public UserManager UserManager
        {
            get
            {
                return Request.GetOwinContext().GetUserManager<UserManager>();
            }
        }

        public SignInManager SignInManager
        {
            get
            {
                return HttpContext.GetOwinContext().Get<SignInManager>();
            }
        }

        private readonly IUserInfoProvider userInfoProvider;

        public BusinessInfoController(IUserInfoProvider userInfoProvider)
        {
            this.userInfoProvider = userInfoProvider;
        }

        [HttpGet]
        public ActionResult BusinessInfo(UserBusinessInfo userBusinessInfo)
        {
            return View(userBusinessInfo);
        }
        
        [HttpGet]
        [ChildActionOnly]
        public ActionResult UserBasicInfo()
        {
            var userId = SignInManager.AuthenticationManager.User.Identity.GetUserId();
            var currentUser = userInfoProvider.GetBasicUserInfo(int.Parse(userId));

            return PartialView(currentUser);
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult SupportedSectors()
        {
            var allSupportedSectors = userInfoProvider.GetSupportedSectors();
            return PartialView(allSupportedSectors);
        }

        //[HttpGet]
        //public ActionResult SupportedCompanies(int sectorId)
        //{
        //    var supportedCompaniesForSector = userInfoProvider.GetSupportedCompanies(sectorId);
        //    return PartialView(supportedCompaniesForSector);
        //}
    }
}

Connect/Controllers/ProfileController.cs
using System.Web;
using System.Web.Mvc;

using ApplicationServices;
using Connect.Helpers;
using Models;
using Models.Profile;
using Data;
using Microsoft.AspNet.Identity.Owin;
using Data.Repository.Implementation;
using Microsoft.AspNet.Identity;
using System;

namespace Connect.Controllers
{
    public class ProfileController : BaseController
    {
        public UserManager UserManager
        {
            get
            {
                return Request.GetOwinContext().GetUserManager<UserManager>();
            }
        }

        private readonly IUserInfoProvider userInfoProvider;
        private readonly ISkillsApplicationService skillsApplicationService;
        private readonly ICommonInfoManager commonInfoProvider;
        private readonly IProfileApplicationService profileApplicationService;

        public ProfileController(IUserInfoProvider userInfoProvider, ISkillsApplicationService skillsApplicationService, ICommonInfoManager commonInfoProvider, IProfileApplicationService profileApplicationService)
        {
            this.userInfoProvider = userInfoProvider;
            this.skillsApplicationService = skillsApplicationService;
            this.commonInfoProvider = commonInfoProvider;
            this.profileApplicationService = profileApplicationService;
        }
        
        public ActionResult SetUserRole(UserType userType)
        {
            var userId = User.Identity.GetUserId();
            var userName = User.Identity.GetUserName();

            switch (userType)
            {
                case UserType.Recruiter:
                    UserManager.AddToRole(int.Parse(userId), "Recruiter");
                    break;
                case UserType.Candidate:
                    UserManager.AddToRole(int.Parse(userId), "Candidate");
                    break;
                default:
                    throw new ArgumentException("No such user type");
            }

            return Json(new { RedirectUrl = Url.Content("~/Profile/Profile?userName=" + userName) }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public new ActionResult Profile(string userName)
        {
            var user = UserManager.FindByName(userName);

            var isRecruiter = UserManager.IsInRole(user.Id, "Recruiter");
            var currentUser = userInfoProvider.GetUserProfile(user.Id);

            if (isRecruiter)
            {
                Session["userNameReadOnly"] = userName;
                if (User.Identity.GetUserName().Equals(userName))
                {
                    Session["userName"] = userName;
                    currentUser.CanEditProfile = true;
                    return View("RecruiterProfile");
                }

                return View("RecruiterProfileReadOnly");
            }

            if (User.Identity.GetUserName().Equals(userName))
            {
                Session["userName"] = userName;
                currentUser.CanEditProfile = true;
                return View(currentUser);
            }

            return View("ProfileReadOnly", currentUser);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NavigationProfileInfo()
        {
            var userId = User.Identity.GetUserId();
            var userDashboardProfile = userInfoProvider.GetUserDashboardProfile(int.Parse(userId));

            return PartialView(userDashboardProfile);
        }

        [Authorize]
        [HttpGet]
        [ChildActionOnly]
        public ActionResult ProfileBasicInfo(string userName)
        {
            var user = UserManager.FindByName(userName);
            var currentUser = userInfoProvider.GetBasicUserInfo(user.Id);

            if (User.Identity.GetUserName().Equals(userName))
            {
                currentUser.CanEditProfile = true;
            }

            return PartialView(currentUser);
        }

        [Authorize]
        [HttpGet]
        [OutputCache(Duration = 60 * 60)]
        public ActionResult Qualifications(string userName)
        {
            var user = UserManager.FindByName(userName);
            var currentUser = userInfoProvider.GetUserProfile(user.Id);

            if (User.Identity.GetUserName().Equals(userName))
            {
                currentUser.CanEditProfile = true;
            }

            return PartialView(currentUser);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddExperience(ExperienceViewModel experience)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();

                experience.UserId = int.Parse(userId);
                userInfoProvider.AddExperience(experience, UserManager);

                return PartialView("Experience", experience);
            }

            return PartialView(experience);
        }

        [Authorize]
        [HttpGet]
        [OutputCache(Duration = 60 * 60)]
        public ActionResult CreatePosition()
        {
            return PartialView("~/Views/RecruiterProfile/AddPosition.cshtml", new AddPosition());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePosition(AddPosition newPosition)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                newPosition.UserId = int.Parse(userId);
                var position = profileApplicationService.Execute(newPosition);

                return Json(position.PositionId, JsonRequestBehavior.AllowGet);
            }

            return Json(new { error = "Could not create position" }, JsonRequestBehavior.DenyGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult GetOpenedPositions(string userName)
        {
            var user = UserManager.FindByName(userName);
            var openedPositions = userInfoProvider.GetCreatedPositions(user.Id);
            return PartialView("~/Views/Dashboard/RecruiterDashboard/CreatedPositions.cshtml", openedPositions);
        }
    }
}

Connect/Views/BusinessInfo/BusinessInfo.cshtml
<div id="businessInfoWrapper">
    <div class="form-group">
        <div class="col-lg-12">
            @Html.Action("SupportedSectors", "BusinessInfo")
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-2">
            @Html.Action("UserBasicInfo", "BusinessInfo")
        </div>
        <div class="col-lg-10">
            <div class="panel panel-default text-center">
                <div id="businessInfo-supportedCompanies">
                    <h2 class="text-center text-info">Select a sector...</h2>
                </div>
            </div>
        </div>
    </div>
</div>

Connect/Views/BusinessInfo/ProfileBasicInfo.cshtml
@model BasicUserInfo

@if (Model.ProfileImage != null)
{
    <div id="basicUserInfo-image">

    </div>
}
else
{
    <div id="basicUserInfo-image">
        <img src="~/Content/Images/profile-image.png"/>
    </div>
}

<div id="basicUserInfo-name">
    <i class="basicUserInfo-align glyphicon glyphicon-user"></i>
    <h2 class="text-info basicUserInfo-margin-left">@(Model.FirstName + " " + Model.LastName)</h2>
</div>
<div id="businessInfo-email">
    <i class="basicUserInfo-align glyphicon glyphicon-envelope"></i>
    <h4 class="text-info basicUserInfo-margin-left"><a href="#">@Model.Email</a></h4>
</div>
<div id="basicUserInfo-country">
    <i class="basicUserInfo-align glyphicon glyphicon-home"></i>
    <h4 class="text-muted basicUserInfo-margin-left">Bulgaria</h4> @*TODO: Show country populated from registration.*@
</div>
<div>
    <i class="basicUserInfo-align glyphicon glyphicon-heart-empty"></i>
    <h4 class="text-muted basicUserInfo-margin-left">@Utils.Gender.Male</h4>
</div>

<div>
    @Html.ActionLink("Edit Profile", "", "", new { @class = "btn btn-primary col-lg-12" })
</div>
<div id="basicUserInfo-joined-on">
    <i class="basicUserInfo-align glyphicon glyphicon-time"></i>
    <h5 class="text-muted basicUserInfo-margin-left">Joined on @Model.DateOfCreation</h5>
</div>

Connect/Views/BusinessInfo/SupportedSectors.cshtml
@model IEnumerable<SupportedSector>

@Html.DropDownList("supportedSector",
        new SelectList(Model.Select(x => new { Value = x.Id, Text = x.Name }), "Value", "Text"),
                        "Select sector", new { id= "supportedSector-dropdown", @class = "form-control" })

Connect/Views/BusinessInfo/UserBasicInfo.cshtml
@model BasicUserInfo

@if (Model.ProfileImage != null)
{
    <div id="basicUserInfo-image">
        @{
            string imageBase64 = Convert.ToBase64String(Model.ProfileImage);
            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
        }
        <img src="@imageSrc"/>
    </div>
}
else
{
    <div id="basicUserInfo-image">
        <img src="~/Content/Images/profile-image.png"/>
    </div>
}

<div id="basicUserInfo-name">
    <i class="basicUserInfo-align glyphicon glyphicon-user"></i>
    <h2 class="text-info basicUserInfo-margin-left">@(Model.FirstName + " " + Model.LastName)</h2>
</div>
<div id="businessInfo-email">
    <i class="basicUserInfo-align glyphicon glyphicon-envelope"></i>
    <h4 class="text-info basicUserInfo-margin-left"><a href="#">@Model.Email</a></h4>
</div>
<div id="basicUserInfo-country">
    <i class="basicUserInfo-align glyphicon glyphicon-home"></i>
    <h4 class="text-muted basicUserInfo-margin-left">@Model.Country.CountryName</h4> @*TODO: Show country populated from registration.*@
</div>
<div>
    <i class="basicUserInfo-align glyphicon glyphicon-heart-empty"></i>
    <h4 class="text-muted basicUserInfo-margin-left">@Utils.Gender.Male</h4>
</div>
<div>
    @Html.ActionLink("Edit Profile", "Profile", "Profile", null, new { @class = "btn btn-primary col-lg-12" })
</div>
<div id="basicUserInfo-joined-on">
    <i class="basicUserInfo-align glyphicon glyphicon-time"></i>
    <h5 class="text-muted basicUserInfo-margin-left">Joined on @Model.DateOfCreation</h5>
</div>